# Main Approaches for Dimensionality Reduction

## Projection

## Manifold Learning

# PCA

## Preserving the Variance

## Principal Components

In [1]:
import pandas as pd
import numpy as np

In [2]:
np.random.seed(42)
m = 60
w1, w2 = 0.1, 0.3
noise = 0.1

angles = np.random.rand(m) * 3 * np.pi / 2 - 0.5
X = np.empty((m,3))
X[:, 0] = np.cos(angles) + np.sin(angles)/2 + noise * np.random.randn(m) / 2
X[:, 1] = np.sin(angles) * 0.7 + noise * np.random.randn(m) / 2
X[:, 2] = X[:, 0] * w1 + X[:, 1] * w2 + noise * np.random.randn(m)

In [3]:
X_centered = X - X.mean(axis = 0)
U, s, Vt = np.linalg.svd(X_centered)
c1 = Vt.T[:,0]
c2 = Vt.T[:,1]

In [4]:
m,n = X.shape

S = np.zeros(X_centered.shape)
S[:n,:n] = np.diag(s)

np.allclose(X_centered, U.dot(S).dot(Vt))

True

In [5]:
W2 = Vt.T[:,:2]
X2D = X_centered.dot(W2)

In [6]:
angles

array([ 1.26497873,  3.98013562,  2.94944019,  2.32111164,  0.23522052,
        0.23510686, -0.22628743,  3.58175892,  2.33268776,  2.83671341,
       -0.40299786,  4.0705925 ,  3.42279353,  0.50062449,  0.35682997,
        0.36427339,  0.93370779,  1.97285643,  1.53549295,  0.87238499,
        2.38328884,  0.15734933,  0.87669922,  1.22643951,  1.64917917,
        3.20005455,  0.44094053,  1.9232727 ,  2.29168789, -0.28110759,
        2.36298767,  0.303576  , -0.19345159,  3.97151775,  4.05043375,
        3.30948276,  0.93545857, -0.03973101,  2.72437217,  1.57416976,
        0.07509163,  1.83346621, -0.33794791,  3.78507144,  0.71947193,
        2.62206271,  0.96890384,  1.95076281,  2.0763115 ,  0.3711061 ,
        4.06905992,  3.15272738,  3.92728446,  3.71677455,  2.31753727,
        3.84422999, -0.08298891,  0.42354748, -0.28687142,  1.03308307])

In [7]:
X

array([[ 0.7039474 ,  0.65945649,  0.3645693 ],
       [-1.0763742 , -0.50036633, -0.21646923],
       [-0.90914129,  0.22798983,  0.05968884],
       [-0.26327638,  0.52076062,  0.31957985],
       [ 1.10617261,  0.17601773,  0.13888377],
       [ 1.0008109 ,  0.15934054,  0.07250963],
       [ 0.87852969, -0.25299137, -0.07699588],
       [-1.13697989, -0.29958862, -0.2851556 ],
       [-0.36237145,  0.50948368,  0.10889779],
       [-0.7732104 ,  0.3332867 ,  0.05678017],
       [ 0.77535051, -0.28414251,  0.01996138],
       [-0.95258223, -0.54563776, -0.17623123],
       [-1.14143853, -0.19599228, -0.17164135],
       [ 1.10180912,  0.27754754,  0.33879858],
       [ 1.12822483,  0.30165509,  0.17685333],
       [ 1.16129536,  0.28698597,  0.47424224],
       [ 0.97281446,  0.60223335,  0.34051818],
       [ 0.05953046,  0.59871039,  0.09985041],
       [ 0.47966775,  0.76970355,  0.17178859],
       [ 0.9661238 ,  0.46601271,  0.28466344],
       [-0.34153172,  0.51072655,  0.096

In [8]:
X_centered

array([[ 5.47136958e-01,  4.82467738e-01,  2.78272202e-01],
       [-1.23318464e+00, -6.77355084e-01, -3.02766325e-01],
       [-1.06595173e+00,  5.10010710e-02, -2.66082639e-02],
       [-4.20086817e-01,  3.43771864e-01,  2.33282748e-01],
       [ 9.49362168e-01, -9.71028359e-04,  5.25866684e-02],
       [ 8.44000462e-01, -1.76482181e-02, -1.37874640e-02],
       [ 7.21719251e-01, -4.29980124e-01, -1.63292983e-01],
       [-1.29379033e+00, -4.76577375e-01, -3.71452702e-01],
       [-5.19181893e-01,  3.32494922e-01,  2.26006880e-02],
       [-9.30020839e-01,  1.56297940e-01, -2.95169326e-02],
       [ 6.18540077e-01, -4.61131262e-01, -6.63357193e-02],
       [-1.10939267e+00, -7.22626519e-01, -2.62528326e-01],
       [-1.29824897e+00, -3.72981033e-01, -2.57938446e-01],
       [ 9.44998681e-01,  1.00558780e-01,  2.52501481e-01],
       [ 9.71414397e-01,  1.24666339e-01,  9.05562297e-02],
       [ 1.00448492e+00,  1.09997216e-01,  3.87945146e-01],
       [ 8.16004024e-01,  4.25244590e-01

In [9]:
X2D_using_svd = X2D

In [10]:
from sklearn.decomposition import PCA

pca = PCA(n_components = 2)
X2D = pca.fit_transform(X)

In [11]:
X2D[:5]

array([[-0.690074  , -0.36150744],
       [ 1.39636097,  0.34497714],
       [ 1.00728461, -0.35025708],
       [ 0.2736333 , -0.50516373],
       [-0.91324535,  0.26290852]])

In [12]:
X2D_using_svd[:5]

array([[-0.690074  , -0.36150744],
       [ 1.39636097,  0.34497714],
       [ 1.00728461, -0.35025708],
       [ 0.2736333 , -0.50516373],
       [-0.91324535,  0.26290852]])