In [1]:
import tensorflow as tf

In [2]:
random_float = tf.random.uniform(shape = ())

zero_vector = tf.zeros(shape=(2))

A = tf.constant([[1.,2.],[3.,4.]])
B = tf.constant([[5.,6.],[7.,8.]])

2022-01-06 17:49:54.998701: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
print(A.shape)
print(A.dtype)
print(A.numpy())

(2, 2)
<dtype: 'float32'>
[[1. 2.]
 [3. 4.]]


In [4]:
C = tf.add(A,B)
D = tf.matmul(A,B)

In [5]:
C

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 6.,  8.],
       [10., 12.]], dtype=float32)>

In [6]:
D

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[19., 22.],
       [43., 50.]], dtype=float32)>

In [7]:
x = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
    y = tf.square(x)
    
y_grad = tape.gradient(y,x)
print(y,y_grad)

tf.Tensor(9.0, shape=(), dtype=float32) tf.Tensor(6.0, shape=(), dtype=float32)


In [8]:
X = tf.constant([[1.,2.],[3.,4.]])
y = tf.constant([[1.],[2.]])
w = tf.Variable(initial_value=[[1.],[2.]])
b = tf.Variable(initial_value=1.)

with tf.GradientTape() as tape:
    L = tf.reduce_sum(tf.square(tf.matmul(X,w) + b -y))
w_grad, b_grad = tape.gradient(L,[w,b])
print(L,w_grad,b_grad)

tf.Tensor(125.0, shape=(), dtype=float32) tf.Tensor(
[[ 70.]
 [100.]], shape=(2, 1), dtype=float32) tf.Tensor(30.0, shape=(), dtype=float32)


In [9]:
import numpy as np

X_raw = np.array([2013, 2014, 2015, 2016, 2017], dtype = np.float32)
y_raw = np.array([12000,14000,15000,16500, 17500], dtype = np.float32)

X = (X_raw - X_raw.min()) / (X_raw.max() - X_raw.min())
y = (y_raw - y_raw.min()) / (y_raw.max() - y_raw.min())

In [10]:
a,b = 0,0

num_epoch = 10000
learning_rate = 5e-4

for e in range(num_epoch):
    y_pred = a*X + b
    grad_a, grad_b = 2 * (y_pred - y).dot(X), 2*(y_pred -y).sum()
    
    a,b = a - learning_rate * grad_a, b - learning_rate * grad_b
print(a,b)

0.9763702027872223 0.057564988337455304


In [12]:
X = tf.constant(X)
y = tf.constant(y)

a = tf.Variable(initial_value = 0.)
b = tf.Variable(initial_value = 0.)
variables = [a,b]

num_epoch = 10000
optimizer = tf.keras.optimizers.SGD(learning_rate = 5e-4)
for e in range(num_epoch):
    with tf.GradientTape() as tape:
        y_pred = a * X + b
        loss = tf.reduce_sum(tf.square(y_pred - y))
    grads = tape.gradient(loss,variables)
    optimizer.apply_gradients(grads_and_vars = zip(grads, variables))

In [14]:
print(variables)

[<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.97637>, <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.057565063>]
